use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc;

/// Optional metadata attached to inbound messages.
///
/// Carries domain-specific context (e.g. email account, mode, subject)
/// that the gateway uses for routing decisions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct MessageMetadata {
    /// Email account name (e.g. "lavoro").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_account: Option<String>,
    /// Email response mode ("assisted", "automatic", "on_demand").
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_mode: Option<String>,
    /// Original email subject line.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_subject: Option<String>,
    /// IMAP Message-ID header for reply threading.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_message_id: Option<String>,
    /// Whether this message requires human approval before the agent can respond.
    #[serde(default)]
    pub requires_approval: bool,
    /// True when this message is a batch digest rather than a single email.
    #[serde(default)]
    pub is_digest: bool,
    /// True when this message is generated by the runtime (scheduler/system),
    /// not by an external human sender.
    #[serde(default)]
    pub is_system: bool,
    /// Scheduler kind ("cron" | "automation") when `is_system` is true.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduler_kind: Option<String>,
    /// Source job identifier for scheduled/system events.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduler_job_id: Option<String>,
    /// Automation run identifier for end-to-end lifecycle tracking.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub automation_run_id: Option<String>,
    /// Web UI run identifier for background/resume tracking.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub web_run_id: Option<String>,
    /// Path to a downloaded file attachment (e.g. from Telegram document).
    /// The gateway routes this to `RagEngine::ingest_file()` for indexing.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attachment_path: Option<String>,
    /// Per-message thinking toggle override from the web UI.
    /// `None` = use model default, `Some(true)` = force on, `Some(false)` = force off.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking_override: Option<bool>,
    /// Thread identifier (Discord thread channel_id, Slack thread_ts).
    /// Used to route replies back to the same thread.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
}

/// Message from a channel to the agent
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InboundMessage {
    pub channel: String,
    pub sender_id: String,
    pub chat_id: String,
    pub content: String,
    pub timestamp: DateTime<Utc>,
    /// Optional metadata for routing decisions (email mode, approval, etc.).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<MessageMetadata>,
}

impl InboundMessage {
    pub fn session_key(&self) -> String {
        format!("{}:{}", self.channel, self.chat_id)
    }
}

/// Optional metadata attached to outbound messages.
///
/// Carries channel-specific routing context (thread IDs, email headers)
/// that channel implementations use for proper reply threading.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OutboundMetadata {
    /// Discord/Slack thread identifier for threaded replies.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
    /// Email In-Reply-To message ID for reply threading.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_message_id: Option<String>,
    /// Email subject for reply Subject line.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub email_subject: Option<String>,
}

/// Build outbound metadata from inbound metadata (thread/email context propagation).
pub fn build_outbound_meta(inbound_meta: Option<&MessageMetadata>) -> Option<OutboundMetadata> {
    let meta = inbound_meta?;
    let has_data =
        meta.thread_id.is_some() || meta.email_message_id.is_some() || meta.email_subject.is_some();
    if !has_data {
        return None;
    }
    Some(OutboundMetadata {
        thread_id: meta.thread_id.clone(),
        email_message_id: meta.email_message_id.clone(),
        email_subject: meta.email_subject.clone(),
    })
}

/// Message from the agent to a channel
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OutboundMessage {
    pub channel: String,
    pub chat_id: String,
    pub content: String,
    /// Optional metadata for channel-specific routing (threading, email headers).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<OutboundMetadata>,
}

/// A streaming text chunk routed to a specific chat session.
/// Used by the gateway to push incremental LLM output to the web UI
/// via the WebSocket stream_sessions map.
#[derive(Debug, Clone)]
pub struct StreamMessage {
    pub chat_id: String,
    pub delta: String,
    pub done: bool,
    /// Optional event type for non-text chunks (e.g. "tool_start", "tool_end").
    pub event_type: Option<String>,
    /// Tool call details for tool_start events
    pub tool_call_data: Option<crate::provider::ToolCallData>,
}

/// Message bus — routes messages between channels and the agent loop
/// using tokio mpsc channels.
pub struct MessageBus {
    pub inbound_tx: mpsc::Sender<InboundMessage>,
    pub inbound_rx: mpsc::Receiver<InboundMessage>,
    pub outbound_tx: mpsc::Sender<OutboundMessage>,
    pub outbound_rx: mpsc::Receiver<OutboundMessage>,
}

impl MessageBus {
    pub fn new(buffer_size: usize) -> Self {
        let (inbound_tx, inbound_rx) = mpsc::channel(buffer_size);
        let (outbound_tx, outbound_rx) = mpsc::channel(buffer_size);
        Self {
            inbound_tx,
            inbound_rx,
            outbound_tx,
            outbound_rx,
        }
    }
}
